# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
  - port: 80
    targetPort: 9898 # Must match below
    name: http-frontend

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - port: 80
    targetPort: 8080 # Must match below
    name: http-backend

---
# 1. FRONTEND: Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: istio-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: stefanprodan/podinfo:latest
        ports:
        - containerPort: 9898 # Explicitly declared for KIA0701
        env:
        - name: PODINFO_BACKEND_URL
          value: "http://backend-svc:80" # This enables the Frontend -> Backend arrow
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: istio-lab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9898
    nodePort: 30012
    name: http-frontend # Explicitly named for KIA0601
  selector:
    app: frontend

---
# 2. BACKEND: Service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: istio-lab
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http-backend
  selector:
    app: backend

---
# 3. BACKEND: Version 1 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  namespace: istio-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: mccutchen/go-httpbin:latest
        ports:
        - containerPort: 8080 # Explicitly declared for KIA0701
---
# 4. BACKEND: Version 2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: istio-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
      - name: backend
        image: mccutchen/go-httpbin:latest
        ports:
        - containerPort: 8080