# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
  - port: 80
    targetPort: 9898 # The Service sends traffic here
    name: http-frontend
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: stefanprodan/podinfo:latest
        ports:
        - containerPort: 9898 # This MUST exist and match the targetPort
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - port: 80
    targetPort: 8080 
    name: http-backend
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
spec:
  template:
    spec:
      containers:
      - name: backend
        image: mccutchen/go-httpbin:latest
        ports:
        - containerPort: 8080 # This line resolves KIA0701 for the backend