apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-lab
  annotations:
    networking.istio.io/service-type: NodePort
    # Optional: Force the specific port 30010
    networking.istio.io/service-nodeport: "30010" 
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
